# Generated by Django 5.1.5 on 2025-02-20 16:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_categoryproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='digitalproduct',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='shop.categoryproduct'),
        ),
    ]
