# Generated by Django 5.1.5 on 2025-02-20 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_digitalproduct_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='digitalproduct',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='digital_products/cover'),
        ),
    ]
