# Generated by Django 5.1.5 on 2025-02-07 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='featured_blog',
            field=models.BooleanField(default=False),
        ),
    ]
