# Generated by Django 5.1.5 on 2025-02-10 17:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_comment_parent_obj'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='parent_obj',
        ),
        migrations.AddField(
            model_name='comment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='replies', to='blog.comment'),
        ),
    ]
