# Generated by Django 5.1.5 on 2025-02-12 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0002_userprofile_first_name_userprofile_last_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='last_name',
        ),
    ]
